### ISSUE TITLE
remove some routes for some languages

### ISSUE THREAD

**Issue by lsmith77** [symfony-cmf/cmf-sandbox#142]
it would be good to show case that the routing doesnt need to be the same for all languages. that being said, we currently do not easily support making menu items only available for some languages, so removing a route in one language just means that the menu will point to another language.

**Comment by damonsson** [comment]
Closed because? Is it possible? Or not planned feature?

**Comment by dbu** [comment]
because we don't have time to do everything we thought of demoing :-) 

the feature is available. if you use the CmfRoutingBundle, there is usually a separate route per locale and you can create routes only for some locales. or create all routes even when the content is not translated.

with the CmfMenuBundle, there is by default just one tree because we assumed it more likely that you want the same navigation in all languages. but you can do one menu per locale and make them different as well.
