### ISSUE TITLE
CSS issues:

### ISSUE THREAD

**Issue by dantleech** [symfony-cmf/cmf-sandbox#312]
Logo is cropped and languages not visible:

![cmfsand1](https://cloud.githubusercontent.com/assets/530801/12530740/b078bdb4-c1e8-11e5-885e-ec2d65baf47d.png)

Edition bar obstructs the header:

![cmfsand2](https://cloud.githubusercontent.com/assets/530801/12530745/df2d638a-c1e8-11e5-8032-b856798efeeb.png)

This could be a usability issue as it is not immediately clear how to remove it.

**Comment by WouterJ** [comment]
Both issues are due to Create.JS. I almost want to propose to remove the CreateJS thing from the Sandbox for now (I'm planning to do a rewrite of CreateBundle, creating a custom CMF toolbar instead of using CreateJS's toolbar).

The first problem is due to https://github.com/bergie/create/issues/217 (it overrides bootstrap styles)

**Comment by dbu** [comment]
could we default the toolbar to minimized? then we would still have it
around for demoing createjs

**Comment by WouterJ** [comment]
@dbu this doesn't fix the style issues with the dropdown menu.

**Comment by dantleech** [comment]
I think defaulting to minimised would still be good -- as long as we have a big arrow or something pointing out where it is.

**Comment by dbu** [comment]
well then lets remove it for now if its broken.
