### ISSUE TITLE
Not sure bug or what ?

### ISSUE THREAD

**Issue by maity-kgz** [symfony-cmf/cmf-sandbox#333]
If you create from admin panel new publishable static page and create publishable menu-node and link to newly created static page (by changing link type to content) its never shown in menu.

Tested on 1.3 locally and on official sandbox.

**Comment by dbu** [comment]
you also need to create a route. but at least in the online demo at http://sandbox.cmf.symfony.com/en/admin/app/demoseocontent/cms/content/company/edit the route part seems to be broken. it does not even show routes for content that already exists and that has a route. i get no js error, so something else must be amiss.

**Comment by dbu** [comment]
if i create the route in the separate route admin and select that it points to a new content, that new content indeed shows up in the menu on the page. so it must be a problem with https://github.com/symfony-cmf/routing-bundle/blob/master/Admin/Extension/RouteReferrersExtension.php (or some edge case with sonata itself)

**Comment by maity-kgz** [comment]
Thanx for your replay dbu. I figured out later that i must create route. But in first place the fact that existing static pages shows in menu "without routes" confused me.

**Comment by dbu** [comment]
there is definitely something broken with the routes embedded on the
content admins. did not find out what, however. hoping somebody finds
time to debug the problem.

**Comment by WouterJ** [comment]
We've had similar issues before: https://github.com/symfony-cmf/cmf-sandbox/issues/316 These were related to Sonata. I'll try to look at this this evening.

**Comment by dbu** [comment]
@WouterJ was https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/pull/397 related to this? do we need to update sonata admin in the sandbox?

in the online sandbox it still does not work, but when i try to add a route i now get "Fatal error: Call to undefined method Symfony\Component\Validator\Context\ExecutionContext::addViolationAt() in /app/vendor/doctrine/phpcr-bundle/Validator/Constraints/ValidPhpcrOdmValidator.php on line 64". 

the fatal error is fixed in phpcr-bundle 1.3.4 but when trying to update the sandbox, i run into other problems, will try to fix those tonight.

**Comment by dbu** [comment]
hm, got myself confused bout that phpcr-bundle 1.3.4 upgrade, was able to upgrade now, see #334

**Comment by WouterJ** [comment]
As far as I can test things, it works perfectly after updating the dependencies ( #335 ). However, updating the dependencies brought in some new issues that we have to fix...

**Comment by wouterj** [comment]
#335 is merged, but this bug still exists. I'll investigate this once again tomorrow.

**Comment by wouterj** [comment]
Tried it again with the new sandbox and things work as expected now.
